django_movie/movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("rating_stars/", views.RatingLessonView.as_view(), name='rating_stars'),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("author/<str:slug>/", views.ActorView.as_view(), name="author_detail"),
]

django_movie/movies/models.py
from django.db import models

from django.urls import reverse
from embed_video.fields import EmbedVideoField


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Category(BaseModel):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(BaseModel):
    """Автор"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="authors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('author_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Genre(BaseModel):
    """Темы"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тема"
        verbose_name_plural = "Темы"


class Movie(BaseModel):
    """Уроки"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2020)
    directors = models.ManyToManyField(Actor, verbose_name="автор", related_name="film_director")
    genres = models.ManyToManyField(Genre, verbose_name="темы")
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    reviews_set = None  # добавил

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        ordering = ['-id']  # добавил 11.12.2022
        verbose_name = "Урок"
        verbose_name_plural = "Уроки"


class MovieShots(BaseModel):
    """Кадры из видео"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Урок", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из урока"
        verbose_name_plural = "Кадры из уроков"


class RatingStar(BaseModel):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(BaseModel):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="урок", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(BaseModel):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="урок", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Videos(BaseModel):
    title = models.CharField("Заголовок", max_length=100)
    video = EmbedVideoField(blank=True, verbose_name='Видео')
    movie = models.ForeignKey(Movie, verbose_name="урок", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = "Видео"

django_movie/movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "id": "contactusername"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "id": "contactemail"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "id": "contactcomment"})
        }


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

django_movie/movies/views.py
# from django.conf import settings
# from django.db import models
from django.db.models import Q  # , OuterRef, Subquery, Case, When
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Movie, Actor, Genre, Rating  # , Category, Reviews
from .forms import ReviewForm, RatingForm


class RatingView:
    def title(self):
        return str("Рейтинг")

    def list_stars(self):
        list_of_stars = range(1, 6)
        return list_of_stars

    def get_rating(self):
        r = Rating.objects.all().values("star", "movie")
        dict_star = {key['movie']: key['star'] for key in r}
        return dict_star

    def get_poster(self):
        return Movie.objects.filter(draft=False).values("poster")


class GenreYear:
    """Темы и года выхода уроков"""

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class RatingLessonView(RatingView, ListView, GenreYear):
    """Фильтр рейтингов"""
    paginate_by = 6

    def get_queryset(self):
        mov_id = Rating.objects.filter(star__in=self.request.GET.getlist("stars")).values('movie')
        queryset = Movie.objects.filter(
            Q(id__in=mov_id)).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["star"] = ''.join([f"star={x}&" for x in self.request.GET.getlist("stars")])
        return context


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class MoviesView(RatingView, GenreYear, ListView):
    """Список уроков"""
    model = Movie
    queryset = Movie.objects.filter(draft=False).order_by('id')
    paginate_by = 3  # кол-во картинок на главной странице


class MovieDetailView(RatingView, GenreYear, DetailView):
    """Полное описание урока"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class AddReview(View):
    """Отзывы"""

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(RatingView, GenreYear, DetailView):
    """Вывод информации о авторе"""
    model = Actor
    template_name = 'movies/author.html'
    slug_field = "name"


class FilterMoviesView(RatingView, ListView, GenreYear):
    """Фильтр уроков"""
    paginate_by = 6

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class JsonFilterMoviesView(ListView):
    """Фильтр уроков в json"""

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    """Добавление рейтинга уроку"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(RatingView, ListView, GenreYear):
    """Поиск уроков"""
    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

django_movie/templates/movies/author.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="col-md-4">
{% endblock sidebar %}

{% block movie %}
    <div class="col-md-8">
        <div class="row">
            <div class="figure col-md-8">
                <img src="{% static 'images/' %}{{ actor.image }}" class="figure-img img-fluid rounded" alt="">
            </div>
            <div class="social col-md-4 text-center">
                <a href="https://github.com/ovvladimir/">
                    <i class="fab fa-github-square fa-8x text-danger"></i>
                </a>
            </div>
        </div>
        <figure class="figure">
            <h4 class="text-primary mt-5">
                О {{ actor.name }}
            </h4>
            <figcaption class="figure-caption">
                {{ actor.description|safe }}
            </figcaption>
        </figure>

    </div>
    </div>
    </div>
{% endblock movie %}

django_movie/templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="py-md-5 py-4 px-5">
        {% block container %}
        <div class="container-fluid py-md-3">
            {% endblock container %}
            <div class="row">
                {% block sidebar %}
                <div class="col-lg-3">
                {% endblock sidebar %}
                {% include 'include/sidebar.html' %}
                </div>
                {% block movie %}
                {% endblock movie %}
            </div>
        </div>
    </section>
{% endblock content %}

django_movie/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% load movie_tag %}
<!-- load embed_video_tags -->
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="col-md-4">
{% endblock sidebar %}

{% block movie %}
    <div class="col-md-8">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col-md-6">
                    <figure class="figure">
                        <img src="{% static 'images/' %}{{movie.poster}}" class="img-fluid img-thumbnail" alt="">
                    </figure>
                </div>
                <div class="col-md-6 pl-lg-4 figure-caption">
                    <h3>
                        {{ movie.title }}
                    </h3>
                    <ul class="ml-0 pl-0" style="list-style: none">
                        <li>
                            <span><b>Год:</b> {% now "Y" %}{% comment %}{{ movie.year }}{% endcomment %}</span>
                        </li>
                        <li>
                            <span><b>Категория:</b> {{ movie.tagline }}</span>
                        </li>
                        <li>
                            <span><b>Автор:</b>
                                {% for director in movie.directors.all %}
                                    <a href="{{ director.get_absolute_url }}">
                                        {{ director.name }}
                                    </a>
                                {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Тема:</b>
                            {% for genre in movie.genres.all %}
                                {{ genre.name }}
                            {% endfor %}
                            </span>
                        </li>
                        <li>
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <span class="mr-2 float-left"><b>Рейтинг: </b>{{ view.get_rating|index:movie.id }}.0</span>
                                {% csrf_token %}
                                <input type="hidden" value="{{ movie.id }}" name="movie">
                                <span class="rating">
                                    {% for k, v in star_form.fields.star.choices %}
                                        {% if k == view.get_rating|index:movie.id %}
                                            <input id="rating{{ k }}" type="radio" name="star" value="{{ k }}" checked="checked">
                                        {% else %}
                                            <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                                        {% endif %}
                                        <label for="rating{{ v }}" class="fas fa-star m-0 pt-md-1">
                                        </label>
                                    {% endfor %}
                                </span>
                            </form>
                        </li>
                        <li><br><br>
                            <p>
                                {{ movie.description }}
                            </p>
                        </li>
                    </ul>
                </div>
            </div>

            {% include "include/school/"|add:movie.title|add:".html" %}

            {% with img=movie.movieshots_set.all %}
            {% if img %}
            <div class="card mb-4 p-4">
                <figure class="figure">
                    {% for image in img %}
                        <p>{{ image.description }}</p>
                        <img src="{{ image.image.url }}" class="img-fluid py-2" alt="">
                    {% endfor %}
                </figure>
            </div>
            {% endif %}
            {% endwith %}

            <!-- VIDEO -->
            {% with name=movie.videos_set.get %}<!-- for name in movie.item_set.all -->
            {% if name %}
                <iframe width="560" height="315" src="{{ name.video }}" frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                </iframe>
            {% endif %}
            {% endwith %}

            {% comment "Закомментировать код" %}
            <video width="560" height="315" playsinline controls preload="metadata">
                <!--source src="{% get_static_prefix %}images/{{ movie.title }}.mp4" type="video/mp4"-->
                <source src="{% static 'images/'|add:movie.title|add:'.mp4' %}" type="video/mp4">
            </video>
            {% endcomment %}

            <div class="row mt-5">
                <div class="form-group">
                    <div class="form-check">
                        <h3 class="text-primary">
                            <span class="badge text-danger float-left" style="font-size: 0.7rem;">
                                {{ movie.reviews_set.count }}
                            </span>
                            Оставить отзыв
                        </h3>
                        <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                              id="formReview">
                            {% csrf_token %}
                            <input class="form-check-input" type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group">
                                <label class="form-check-label">Ваш комментарий *</label>
                                {{ form.text }}
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0">
                                    <label class="form-check-label">Имя *</label>
                                    {{ form.name }}
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3">
                                    <label class="form-check-label">Email *</label>
                                    {{ form.email }}
                                </div>
                                {{ form.captcha }}
                            </div>
                            <button type="submit" class="mt-3 btn btn-danger btn-block py-3">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
            {% for review in movie.get_review %}
            <div class="media mt-4">
                <i class="fas fa-2x rounded-circle bg-primary py-3 px-2">&#x1F440;</i>
                <div class="media-body">
                    <h5 class="mt-0 ml-3">{{ review.name }}</h5>
                    <i class="mt-2 ml-3">{{ review.text }}</i><br>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-4">
                            <i class="fas fa-3x rounded-circle bg-primary py-2">&#x1F393;</i>
                            <div class="media-body">
                                <h5 class="mt-0 ml-3">{{ rew.name }}</h5>
                                <i class="mt-2 ml-3">{{ rew.text }}</i>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h4 class="text3D text-center">
            Войдите в свой аккаунт или зарегистрируйтесь для просмотра видео и другой информации на сайте
        </h4>
        {% endif %}
    </div>
    </div>
    </div>

    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }

        // Add star rating
        const rating = document.querySelector('form[name=rating]');
        rating.addEventListener("change", function (e) {
            // Получаем данные из формы
            let data = new FormData(this);
            fetch(`${this.action}`, {
                method: 'POST',
                body: data
            })
                .then(response => alert("Рейтинг установлен"))
                .catch(error => alert("Ошибка"))
        });
    </script>

{% endblock movie %}

django_movie/templates/movies/movie_list.html
{% extends 'movies/base.html' %}
{% load static movie_tag %}
{% block title %} PySchool {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="col-md-9 order-first order-lg-2">
        <div id="carouselExampleIndicators" class="carousel slide row" data-ride="carousel" style="background: #44475a;">
          <ol class="carousel-indicators">
          {% for _ in view.get_poster %}
            <li data-target="#carouselExampleIndicators" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
          {% endfor %}
          </ol>
          <div class="carousel-inner col-xl-3 col-md-4 p-1">
          {% for movie in view.get_poster %}
            <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
              <img src="{% static 'images/' %}{{movie.poster}}" height="234">
            </div>
          {% endfor %}
          </div>
          <div class="col-xl-9 col-md-8 my-auto" id="font" style="background: rgba(0, 0, 0, 0);">
            <p><br>
                <span class="text-danger ml-md-3">Здесь вы вы можете посмотреть</span>
                <span class="text-primary">видеоуроки с пояснением кода</span>
                <span class="text-warning">на языке программирования</span>
                <span class="text-white">Python</span>
                <span class="text-primary">и пройти путь от разработки консольных приложений</span>
                <span class="text-warning">до приложений,</span>
                <span class="text-white">работающих в web-браузерах.</span>
                <span class="text-warning">Начнем с шахмат.</span><br>
                <span class="text-danger ml-md-5">Регистрируйтесь и наслаждайтесь!</span>
            </p>
            <pre><code class="python p-0" style="background: rgba(0, 0, 0, 0);">
            if registration is True:
                login()
            <i class='fas fa-mug-hot float-right fa-2x'></i></code></pre>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4">
                    <div class="figure text-center mt-md-4">
                        <img src="{% static 'images/' %}{{movie.poster}}" class="figure-img img-fluid img-thumbnail" alt="">
                        <div class="figure-caption">
                            <h4 class="mt-md-4">
                                {% if user.is_authenticated %}
                                <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                                {% else %}
                                <a type="button" data-toggle="modal" data-target="#exampleModalCenter1">{{ movie.title }}</a>
                                {% endif %}
                            </h4>
                            <div class="figure-caption text-danger">
                                <p>{{ movie.tagline }}</p>
                            </div>
                            <div class="rating_">
                              {% for n in view.list_stars %}
                                <i class="{% if n > view.get_rating|index:movie.id %}far{% else %}fas{% endif %} fa-star text-warning"></i>
                              {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mt-5">
            {% include 'include/pagination.html' %}
        </div>
    </div>
    <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Внимание!</h5>
            <button type="button" class="close text-danger bg-light py-1 px-2" data-dismiss="modal" aria-label="Close"
                    data-toggle="tooltip" data-placement="left" title="Закрыть">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Войдите в свой аккаунт или зарегистрируйтесь для просмотра видео и другой информации на сайте.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>
{% endblock movie %}